### PR TITLE
Initial pass at icons, part 5!

### PR DESCRIPTION
**Pull request by esuts**

### CODE REVIEW

**Comment by esuts** [comment]
Last batch for the initial pass at icons!  I think now I can focus more on general layout stuff.

**Comment by madhephaestus** [comment]
Awesome!!

**Comment by esuts** [comment]
They totally aren't perfect and will need more work, but at least they all have something in place now.  Upward and onward.

**Comment by madhephaestus** [comment]
DOOOD, i love the little person icon for the creatures! I met with @egolden-bowler today and he wants to help out wiht UI bits.

**Comment by esuts** [comment]
Nice, definitely enough to go around. I'm gonna try and start writing up
some tickets on here to track some of it, too.

**Comment by egolden-bowler** [comment]
Hey Eric, I'll be helping you out with User Interface and the like. If you need to get in touch with me I'm at practicallygolden@gmail.com .

**Pull request merged**
